basePath: /api/v1
definitions:
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  models.Tag:
    properties:
      created_at:
        type: string
      deleted_at:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      name:
        type: string
      todos:
        items:
          $ref: '#/definitions/models.Todo'
        type: array
      updated_at:
        type: string
    type: object
  models.Todo:
    properties:
      active:
        type: boolean
      created_at:
        type: string
      deadline:
        type: string
      deleted_at:
        $ref: '#/definitions/gorm.DeletedAt'
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      status_id:
        type: integer
      tags:
        items:
          $ref: '#/definitions/models.Tag'
        type: array
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
  models.User:
    properties:
      created_at:
        type: string
      deleted_at:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      password:
        type: string
      todos:
        items:
          $ref: '#/definitions/models.Todo'
        type: array
      updated_at:
        type: string
      username:
        type: string
    type: object
  schemas.AuthInputData:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  schemas.TodoRequest:
    properties:
      active:
        type: boolean
      deadline:
        type: string
      description:
        type: string
      name:
        type: string
      status_id:
        type: integer
      user_id:
        type: integer
    required:
    - name
    - user_id
    type: object
  schemas.TodoResponse:
    properties:
      active:
        type: boolean
      deadline:
        type: string
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      status_id:
        type: integer
      user_id:
        type: integer
    required:
    - name
    - user_id
    type: object
host: localhost:8080
info:
  contact:
    email: perestavlad@gmail.com
    name: Vladyslav Peresta
    url: https://github.com/Vlad-Peresta
  description: API for working with the Todo List.
  title: Todo List API
  version: 1.0.0
paths:
  /auth/login:
    post:
      description: Login User
      parameters:
      - description: Authentication Data
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/schemas.AuthInputData'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.AuthInputData'
        "400":
          description: Bad Request
          schema: {}
      summary: Login User
      tags:
      - auth
  /auth/signup:
    post:
      description: Create User record
      parameters:
      - description: Authentication Data
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/schemas.AuthInputData'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.AuthInputData'
        "400":
          description: Bad Request
          schema: {}
      summary: Create User record
      tags:
      - auth
  /auth/user/profile:
    get:
      description: Get user profile
      parameters:
      - default: Bearer <Access token>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.User'
        "400":
          description: Bad Request
          schema: {}
      summary: Get user profile
      tags:
      - auth
  /todos:
    get:
      description: Get all Todo records
      parameters:
      - default: Bearer <Access token>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Todo'
            type: array
        "400":
          description: Bad Request
          schema: {}
      summary: Get all Todo records
      tags:
      - todos
    post:
      description: Create Todo record
      parameters:
      - default: Bearer <Access token>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Request Body
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/schemas.TodoRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/schemas.TodoResponse'
        "400":
          description: Bad Request
          schema: {}
      summary: Create Todo record
      tags:
      - todos
  /todos/{id}:
    delete:
      description: Delete Todo record
      parameters:
      - default: Bearer <Access token>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Todo ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Todo'
            type: array
        "400":
          description: Bad Request
          schema: {}
      summary: Delete Todo record
      tags:
      - todos
    get:
      description: Get Todo record by ID
      parameters:
      - default: Bearer <Access token>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Todo ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Todo'
        "400":
          description: Bad Request
          schema: {}
      summary: Get Todo record by ID
      tags:
      - todos
    put:
      description: Update Todo record
      parameters:
      - default: Bearer <Access token>
        description: Insert your access token
        in: header
        name: Authorization
        required: true
        type: string
      - description: Todo ID
        in: path
        name: id
        required: true
        type: integer
      - description: Request Body
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/schemas.TodoRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Todo'
        "400":
          description: Bad Request
          schema: {}
      summary: Update Todo record
      tags:
      - todos
swagger: "2.0"
